name: Build Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go Version
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Build Linux
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o gonalmatrix ./cmd/gonalmatrix

      - name: Build FreeBSD
        run: CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -ldflags="-w -s" -o gonalmatrix ./cmd/gonalmatrix
